---
- ansible.builtin.import_tasks: checks.yml

- name: ensure docker is installed
  ansible.builtin.include_role:
    name: docker-host
    tasks_from: install.yml

- ansible.builtin.import_tasks: install-deps.yml
- ansible.builtin.import_tasks: install.yml
