---

- name: Add directories for Munin local plugins if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /usr/local/share/munin/
    - /usr/local/share/munin/plugins/
  tags:
    - munin

- name: Install some Munin plugins (not enabled yet)
  ansible.builtin.copy:
    src: 'plugins/{{ item }}'
    dest: '/usr/share/munin/plugins/{{ item }}'
    mode: "0755"
  loop:
    - dhcp_pool
    - linux_psi
  tags:
    - munin

- name: Copy Munin local plugins
  ansible.builtin.copy:
    src: 'plugins/{{ item }}'
    dest: '/usr/local/share/munin/plugins/{{ item }}'
    mode: "0755"
  loop:
    - ipmi_
  tags:
    - munin

- name: Ensure some Munin plugins are disabled
  ansible.builtin.file:
    path: '/etc/munin/plugins/{{ item }}'
    state: absent
  loop:
    - http_loadtime
    - exim_mailqueue
    - exim_mailstats
    - nfsd
    - nfsd4
    - nfs_client
    - nfs4_client
  notify: restart munin-node
  tags:
    - munin

- name: Ensure some Munin plugins are enabled
  ansible.builtin.file:
    src: "/usr/share/munin/plugins/{{ item }}"
    dest: "/etc/munin/plugins/{{ item }}"
    state: link
  loop:
    - meminfo
    - netstat_multi
    - tcp
    - postfix_mailqueue
    - postfix_mailstats
    - postfix_mailvolume
    - linux_psi
  notify: restart munin-node
  tags:
    - munin

- name: Enable sensors_ plugin on dedicated hardware
  ansible.builtin.file:
    src: /usr/share/munin/plugins/sensors_
    dest: "/etc/munin/plugins/sensors_{{ item }}"
    state: link
  with_items:
    - fan
    - temp
  when: ansible_virtualization_role == "host"
  notify: restart munin-node
  tags:
    - munin

- name: Enable ipmi_ plugin on dedicated hardware
  ansible.builtin.file:
    src: /usr/local/share/munin/plugins/ipmi_
    dest: "/etc/munin/plugins/ipmi_{{ item }}"
    state: link
  when: ansible_virtualization_role == "host"
  notify: restart munin-node
  with_items:
    - fans
    - temp
    - power
    - volts
    - amp
  tags:
    - munin

- name: Ensure ipmitool is installed on dedicated hardware
  ansible.builtin.apt:
    name: ipmitool
    state: present
  when: ansible_virtualization_role == "host"
  notify: restart munin-node
  tags:
    - munin

- name: adjustments for grsec kernel
  ansible.builtin.blockinfile:
    dest: /etc/munin/plugin-conf.d/munin-node
    marker: "# {mark} ANSIBLE MANAGED GRSECURITY CUSTOMIZATIONS"
    block: |

      [processes]
      user root

      [vmstat]
      user root

      [swap]
      user root
  when: ansible_kernel is search("-grs-")
  tags:
    - munin

