---

- name: Look for legacy apt keyring
  ansible.builtin.stat:
    path: /etc/apt/trusted.gpg
  register: _trusted_gpg_keyring
  tags:
    - apt

- name: Evolix embedded GPG key is absent
  ansible.builtin.apt_key:
    id: "B8612B5D"
    keyring: /etc/apt/trusted.gpg
    state: absent
  tags:
    - apt
  when: _trusted_gpg_keyring.stat.exists

- name: Fetch packages
  ansible.builtin.package_facts:
    manager: auto

- name: Copy keyring package
  ansible.builtin.copy:
    src: evolix-archive-keyring_0~2025_all.deb
    dest: /tmp/evolix-archive-keyring.deb
    mode: "0644"
    owner: root
    group: root
  when: "'evolix-archive-keyring' not in ansible_facts.packages"
  tags:
    - apt

- name: Install Evolix keyring package
  ansible.builtin.apt:
    deb: /tmp/evolix-archive-keyring.deb
    # deb: https://pub.evolix.org/evolix/pool/main/e/evolix-archive-keyring/evolix-archive-keyring_0~2025_all.deb
    state: present
  when:
    - not ansible_check_mode
    - "'evolix-archive-keyring' not in ansible_facts.packages"
  tags:
    - apt

- name: Evolix public list is installed
  ansible.builtin.template:
    src: evolix_public.sources.j2
    dest: /etc/apt/sources.list.d/evolix_public.sources
    force: true
    mode: "0644"
  register: apt_evolix_public
  tags:
    - apt

- name: Apt update
  ansible.builtin.apt:
    update_cache: true
  tags:
    - apt
  when: apt_evolix_public is changed
