---

- name: "Add php-multi sudoers file"
  ansible.builtin.copy:
    src: "etc/sudoers.d/php-multi"
    dest: "/etc/sudoers.d/php-multi"
    mode: "0600"
    validate: "visudo -cf %s"

- ansible.builtin.include_role:
    name: "remount-usr"

- name: "/usr/local/bin/phpContainer"
  ansible.builtin.copy:
    src: "usr/local/bin/phpContainer"
    dest: "/usr/local/bin/phpContainer"
    mode: "preserve"

- name: "Create /etc/skel/.local/bin"
  ansible.builtin.file:
    path: "/etc/skel/.local/bin"
    state: "directory"
    mode: "755"

- name: "Create /etc/skel/.local/bin/php"
  ansible.builtin.file:
    src: "/usr/local/bin/phpContainer"
    dest: "/etc/skel/.local/bin/php"
    state: "link"
