[Service]
StateDirectory=prometheus-node-exporter
ExecStart=
ExecStart=/usr/bin/prometheus-node-exporter \
            @/etc/prometheus/node-exporter/evolinux-default.args \
            @/etc/prometheus/node-exporter/evolinux-custom.args
