#Type Path                                     Mode User Group Age         Argument
# XXX Need since podman-systemd.unit doesn't support optional "Mount"
# https://github.com/containers/podman/issues/26719
# FIXME maybe not needed
# /etc/tmpfiles.d/php-multi.conf:4: Duplicate line for path "/run/mysqld", ignoring.
# it's in /usr/lib/tmpfiles.d/mariadb.conf already
d     /run/mysqld                              0755 -    -     -           -
