---

- name: Remount /usr read-write
  ansible.builtin.include_role:
    name: remount-usr
  when: not ansible_check_mode

- name: Create /etc/evolinux
  ansible.builtin.file:
    path: /etc/evolinux
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Official sources.list
  ansible.builtin.set_fact:
    official:
    # /!\ Keep list in sync with maj.sh/hotfix-allowed-sources.yml
      - system.sources
      - security.sources
      - evolix_public.sources
      - backports.sources
      # sury.sources
      - evolix_sury.sources
      - hp.sources
      - hwraid.le-vert.net.sources
      # postgresql.sources
      - evolix_public.list
      - backports.list
      - extended-lts.list

- name: Create /etc/apt/listupgrade{,-external}-sources.list.d directories
  ansible.builtin.file:
    path: "/etc/apt/{{ item }}-sources.list.d"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - listupgrade
    - listupgrade-external

- name: List active sources
  ansible.builtin.find:
    paths: /etc/apt/sources.list.d
    file_type: file
    patterns:
      - '*.sources'
      - '*.list'
  register: found_external

- name: Initiate external list
  ansible.builtin.set_fact:
    external: []

- name: Add every sources to external
  ansible.builtin.set_fact:
    external: "{{ external + [ item.path | regex_replace('^/etc/apt/sources.list.d/', '') ] }}"
  loop: "{{ found_external.files }}"

- name: Remove official sources from external
  ansible.builtin.set_fact:
    external: "{{ external | difference(official) }}"

- name: Enable allowed sources
  ansible.builtin.file:
    src: "../sources.list.d/{{ item }}"
    dest: "/etc/apt/listupgrade-sources.list.d/{{ item }}"
    state: link
  ignore_errors: true
  loop: "{{ official }}"

- name: Ensure external sources are not enabled
  ansible.builtin.file:
    path: "/etc/apt/listupgrade-sources.list.d/{{ item }}"
    state: absent
  ignore_errors: true
  loop: "{{ external }}"

- name: Enable external sources
  ansible.builtin.file:
    src: "../sources.list.d/{{ item }}"
    dest: "/etc/apt/listupgrade-external-sources.list.d/{{ item }}"
    state: link
  loop: "{{ external }}"

# listupgrade.sh

- name: Copy listupgrade script
  ansible.builtin.copy:
    src: upstream/listupgrade.sh
    dest: "/usr/local/sbin/listupgrade.sh"
    mode: "0700"
    owner: root
    group: root
    force: true

- name: Copy listupgrade config
  ansible.builtin.template:
    src: listupgrade.cnf.j2
    dest: /etc/evolinux/listupgrade.cnf
    mode: "0600"
    owner: root
    group: root
    force: false

- name: Copy listupgrade-ext config
  ansible.builtin.template:
    src: listupgrade-ext.cnf.j2
    dest: /etc/evolinux/listupgrade-ext.cnf
    mode: "0600"
    owner: root
    group: root
    force: false

- name: Cron.d is present
  ansible.builtin.file:
    path: "/etc/cron.d"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Enable listupgrade cron
  ansible.builtin.cron:
    name: "listupgrade.sh"
    cron_file: "listupgrade"
    user: root
    job: "/usr/local/sbin/listupgrade.sh --cron{{ listupgrade_cron_force | bool | ternary(' --force','') }}"
    minute: "{{ listupgrade_cron_minute }}"
    hour: "{{ listupgrade_cron_hour }}"
    weekday: "{{ listupgrade_cron_weekday }}"
    day: "{{ listupgrade_cron_day }}"
    month: "{{ listupgrade_cron_month }}"
    state: "{{ listupgrade_cron_enabled | bool | ternary('present','absent') }}"

# old-kernel-autoremoval

- name: old-kernel-autoremoval.sh is present
  ansible.builtin.copy:
    src: "upstream/old-kernel-autoremoval.sh"
    dest: "/usr/local/sbin/old-kernel-autoremoval"
    owner: root
    group: root
    mode: "0755"

# minor-upgrade

- name: Upload minor-upgrade.sh
  ansible.builtin.copy:
    src: "upstream/minor-upgrade.sh"
    dest: "/usr/local/sbin/minor-upgrade"
    owner: root
    group: root
    mode: "0755"

- name: Hooks are present
  ansible.builtin.copy:
    src: upstream/minor-upgrade-hooks/
    dest: /etc/evolinux/minor-upgrade-hooks/
    owner: root
    group: root
    directory_mode: "0750"
    mode: "0750"

- name: Add new alias in global profile
  ansible.builtin.lineinfile:
    dest: "/etc/profile.d/evolinux.sh"
    line: 'alias maj="TMOUT=0; sudo -k /usr/local/sbin/minor-upgrade"'
    regexp: "^alias maj="
    create: True
    mode: "0644"
    owner: root
    group: root

- name: Add ext alias in global profile
  ansible.builtin.lineinfile:
    dest: "/etc/profile.d/evolinux.sh"
    line: 'alias ext="TMOUT=0; sudo -k /usr/local/sbin/minor-upgrade --external"'
    regexp: "^alias ext="
    create: True
    mode: "0644"
    owner: root
    group: root
