---

- name: Backports repository is configured
  ansible.builtin.include_role:
    name: evolix/apt
    tasks_from: backports.yml
  tags:
    - nginx
    - packages

- name: APT cache is updated
  ansible.builtin.apt:
    update_cache: yes
  tags:
    - nginx
    - packages
