---

- name: "Check if index file exists"
  ansible.builtin.stat:
    path: /var/www/index.html
  register: _server_index

- name: replace server-status suffix in default site index
  ansible.builtin.replace:
    dest: /var/www/index.html
    regexp: '__SERVERSTATUS_SUFFIX__'
    replace: "{{ nginx_serverstatus_suffix }}"
  when: _server_index.stat.exists

- name: add server-status suffix in default site index if missing
  ansible.builtin.replace:
    dest: /var/www/index.html
    regexp: '"/server-status-[^"]*"'
    replace: '"/server-status-{{ nginx_serverstatus_suffix }}"'
  when: _server_index.stat.exists

- name: add server-status suffix in default VHost
  ansible.builtin.replace:
    dest: /etc/nginx/sites-available/evolinux-default.conf
    regexp: 'location /server-status-[^ ]* +{'
    replace: 'location /server-status-{{ nginx_serverstatus_suffix }} {'
  when: not ansible_check_mode
  notify: reload nginx

- name: add server-status suffix in nagios conf
  ansible.builtin.replace:
    dest: /etc/nagios/nrpe.d/evolix.cfg
    regexp: '/server-status-NNNNN '
    replace: '/server-status-{{ nginx_serverstatus_suffix }} '
  when: not ansible_check_mode
