# ANSIBLE MANAGED
#
# Don't log again audit logs, since auditd writes on it's own in /var/lib/audit
#
# But we need rsyslog to handle a copy of the audit log, so it's sent to adm00
# as audisp-syslog doesn't not seems to be able to do it on it's own. 
# We write into /dev/null instead of ignoring the lines, so it's also sent to the
# remote syslog server
:programname, startswith, "audisp-syslog" {
  /dev/null
}
