#
# Ansible managed
#
# See https://gitea.evolix.org/evolix/ansible-roles

# References: 
# - https://cyber.gouv.fr/sites/default/files/2014/01/NT_OpenSSH.pdf
# - https://infosec.mozilla.org/guidelines/openssh

# Disable TCP & X11 Forwarding
X11Forwarding no
#AllowTcpForwarding no

# Keep only modern algs.
KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com

# Allow 4 auth attempts
MaxAuthTries 4

PermitRootLogin no
PermitEmptyPasswords no
PermitUserEnvironment no

# Enforce authentication with ssh keys
AuthenticationMethods publickey

ClientAliveInterval 300
ClientAliveCountMax 0
LoginGraceTime 60