---

- ansible.builtin.fail:
    msg: only compatible with Debian >= 8
  when:
    - ansible_distribution != "Debian" or ansible_distribution_major_version is version('8', '<')

- name: Starting with Debian 13, packweb-apache-v2 is used
  ansible.builtin.include_role:
    name: packweb-apache-v2
  when:
      - ansible_distribution_major_version is version('13', '>=')
      - not packweb_really_v1

- name: Proceed with the installation
  ansible.builtin.import_tasks: install.yml
  when:
      - ansible_distribution_major_version is version('13', '<') or packweb_really_v1

