---

### Install dependencies

- name: "Install dependencies"
  ansible.builtin.apt:
    name: [ bash-completion, nagios-nrpe-plugin, gawk ]
    state: present

- name: "Remount /usr RW after apt hook put it RO"
  ansible.builtin.include_role:
    name: remount-usr


# Do not execute in check mode, because tmp_path does not exists
# TODO: package monitoringctl in a debian package
- name: Install monitoringctl
  when: not ansible_check_mode
  block:

  ### Get upstream

    - name: "Generate random string for /tmp dir"
      ansible.builtin.set_fact:
        tmp_path: /tmp/monitoringctl_{{ lookup('community.general.random_string', length=12, special=false) }}

    - name: Create tmp dir
      delegate_to: localhost
      become: false
      ansible.builtin.file:
        path: "{{ tmp_path }}"
        state: directory
      changed_when: false

    - name: "Download monitoringctl files from Gitea to localhost in /tmp"
      delegate_to: localhost
      become: false
      ansible.builtin.get_url:
        url: "https://gitea.evolix.org/evolix/monitoringctl/raw/branch/{{ monitoringctl_branch }}/{{ item }}"
        dest: "{{ tmp_path }}/{{ item }}"
      loop:
        - alerts_wrapper.py
        - check-local
        - check-local_completion
        - monitoringctl
        - monitoringctl_common
        - monitoringctl_common.py
        - monitoringctl_completion
      changed_when: false
    
    
    ### Prepare files copy
    
    - name: "dir /usr/local/lib/monitoringctl/ exists"
      ansible.builtin.file:
        path: /usr/local/lib/monitoringctl/
        state: directory
        mode: "0755"
  
    - name: "Directory /var/lib/monitoringctl/ exists"
      ansible.builtin.file:
        path: /var/lib/monitoringctl/
        state: directory
        mode: "0755"
    
    - name: "Directory /etc/bash_completion.d exists"
      ansible.builtin.file:
        path: /etc/bash_completion.d
        state: directory
        mode: "0755"
    
    
    ### Push files
    
    - name: "Copy monitoringctl_common lib"
      ansible.builtin.copy:
        src: "{{ tmp_path }}/monitoringctl_common"
        dest: /usr/local/lib/monitoringctl/common
        mode: "0644"
        force: true
    
    - name: "Copy monitoringctl_common.py lib (for alerts_wrapper.py)"
      ansible.builtin.copy:
        src: "{{ tmp_path }}/monitoringctl_common.py"
        dest: /usr/local/lib/monitoringctl/common.py
        mode: "0644"
        force: true
    
    - name: "Copy alerts_wrapper"
      ansible.builtin.copy:
        src: "{{ tmp_path }}/alerts_wrapper.py"
        dest: "{{ monitoringctl_wrapper_path }}"
        group: staff
        mode: "0755"
        force: true
    
    - name: "Copy monitoringctl"
      ansible.builtin.copy:
        src: "{{ tmp_path }}/monitoringctl"
        dest: /usr/local/bin/monitoringctl
        mode: "0755"
        force: true
    
    - name: "Copy monitoringctl_completion script"
      ansible.builtin.copy:
        src: "{{ tmp_path }}/monitoringctl_completion"
        dest: /etc/bash_completion.d/monitoringctl
        mode: "0644"
        force: true
    
    - name: "Copy check-local (it's just a wrapper calling 'monitoringctl check' for backward compatibility)"
      ansible.builtin.copy:
        src: "{{ tmp_path }}/check-local"
        dest: /usr/local/bin/check-local
        owner: root
        group: root
        mode: "0755"
        force: true
    
    - name: "Copy completion for check-local"
      ansible.builtin.copy:
        src: "{{ tmp_path }}/check-local_completion"
        dest: /etc/bash_completion.d/check-local
        mode: "0755"
    
    - name: "Remove tmp dir on localhost"
      delegate_to: localhost
      become: false
      ansible.builtin.file:
        path: "{{ tmp_path }}"
        state: absent
      changed_when: false


### Configuration

- name: "nagios user can run monitoringctl enable with sudo (used by alerts_wrapper)"
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/monitoringctl
    regexp: "nagios.*alerts_switch"
    line: "nagios           ALL = NOPASSWD:/usr/local/bin/monitoringctl enable *"
    create: true
    mode: "0640"
    validate: "visudo -c -f %s"

- name: "Remove nagios sudoer for old alerts_switch"
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/monitoringctl
    regexp: "nagios.*alerts_switch"
    state: "absent"
    validate: "visudo -c -f %s"

# Do not remove alerts_switch for now, so as not to break existing crons
#- name: "alerts_switch is removed"
#  ansible.builtin.file:
#    path: "{{ item }}"
#    state: absent
#  loop:
#    - "/usr/share/scripts/alerts_switch"
#    - "/usr/local/bin/alerts_switch"

# Do not remove old alerts_wrapper for now, so as not to break existing crons
#- name: "Old alerts_wrapper are removed"
#  ansible.builtin.file:
#    path: "{{ nagios_plugins_directory }}/alerts_wrapper"
#    state: "absent"

- name: "monitoringctl is not in /usr/local/sbin/"
  ansible.builtin.file:
    path: /usr/local/sbin/monitoringctl
    state: absent


