# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/jessie64"

  config.vm.synced_folder "./vagrant_share/", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 2
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # Master
  config.vm.define :default do |default|
    default.vm.hostname = "default"
    default.vm.provision :ansible, run: "always" do |ansible|
      ansible.limit = "default"
      ansible.playbook = "vagrant.yml"
      # ansible.tags = "mysql"
      # ansible.raw_arguments = ["-b", "--ask-vault-pass"]
      ansible.raw_arguments = ["-vv"]
    end
  end

end
