---
- name: reload systemd
  ansible.builtin.systemd:
    daemon-reload: yes

- name: restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: yes

- name: restart munin-node
  ansible.builtin.service:
    name: munin-node
    state: restarted
