---

# WARNING: This task file is invoked directly from some playbooks
# Do not change it significantly without verifying not to break those playbooks.

- name: "Remount /usr if needed"
  ansible.builtin.include_role:
    name: remount-usr

- name: Previous autosysadmin restart directory is renamed
  command:
    cmd: mv "/usr/share/scripts/autosysadmin/auto" "{{ autosysadmin_agent_auto_dir }}"
    removes: "/usr/share/scripts/autosysadmin/auto"
    creates: "{{ autosysadmin_agent_auto_dir }}" 

- name: Create autosysadmin directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0750"
  loop:
    - "{{ autosysadmin_agent_bin_dir }}"
    - "{{ autosysadmin_agent_lib_dir }}"
    - "{{ autosysadmin_agent_auto_dir }}"

- name: Copy libraries
  ansible.builtin.copy:
    src: "upstream/lib/"
    dest: "{{ autosysadmin_agent_lib_dir }}/"
    owner: root
    group: root
    mode: "0750"

- name: Copy repair scripts
  ansible.builtin.copy:
    src: "upstream/repair/"
    dest: "{{ autosysadmin_agent_bin_dir }}/"
    owner: root
    group: root
    mode: "0750"

- name: Copy other utilities
  ansible.builtin.copy:
    src: "upstream/bin/"
    dest: "{{ autosysadmin_agent_bin_dir }}/"
    owner: root
    group: root
    mode: "0750"
