---

- name: The list of all repair scripts is composed.
  ansible.builtin.set_fact:
    autosysadmin_repair_scripts: "{{ lookup('ansible.builtin.fileglob', '../../../autosysadmin/agent/repair/repair_*', wantlist=True) | map('basename') | sort }}"

- name: Install dependencies
  ansible.builtin.import_tasks: dependencies.yml

- name: Install autosysadmin
  ansible.builtin.import_tasks: install.yml

- name: Configure autosysadmin
  ansible.builtin.import_tasks: config.yml

- name: Crontab configuration
  ansible.builtin.import_tasks: crontab.yml

- name: NRPE configuration
  ansible.builtin.import_tasks: nrpe.yml

- name: sudo configuration
  ansible.builtin.import_tasks: sudo.yml

- name: rsyslog configuration
  ansible.builtin.import_tasks: rsyslog.yml

- name: logrotate configuration
  ansible.builtin.import_tasks: logrotate.yml

- name: Install latest version of dump-server-state
  ansible.builtin.include_role:
    name: evolinux-base
    tasks_from: dump-server-state.yml
