#!/bin/sh

set -u

final_rc=0
summary=""
details=""

is_alert5_enabled() {
  # It's not very clear how to reliably detect if a SysVinit script
  # wrapped in a systemd unit is enabled or not.
  # Even when the script is not started in any run level, systemd says "active".
  # So we test the SysVinit script path:
  # if present, we test for an rc2.d symlink
  # if missing, we ask systemd if a unit is active or not.
  if test -f /etc/init.d/alert5; then
    test -f /etc/rc2.d/S*alert5
  else
    systemctl is-enabled alert5 | grep -q "^enabled$"
  fi
}

is_minifirewall_enabled() {
  # TODO: instead of nested conditionals, we could loop with many possible paths
  # and grep the first found, or error if none is found
  if [ -f /etc/systemd/system/minifirewall.service ]; then
    systemctl is-enabled minifirewall > /dev/null 2>&1
  else
    if test -f /etc/rc2.d/S*alert5; then
      grep -q "^/etc/init.d/minifirewall" /etc/rc2.d/S*alert5
    else
      if test -f /usr/share/scripts/alert5.sh; then
        grep -q "^/etc/init.d/minifirewall" /usr/share/scripts/alert5.sh
      else
        return_critical "No Alert5 scripts has been found."
      fi
    fi
  fi
}

is_minifirewall_started() {
  if [ -f /etc/systemd/system/minifirewall.service ]; then
    systemctl is-active minifirewall > /dev/null 2>&1
  else
    if test -x /usr/share/scripts/minifirewall_status; then
      /usr/share/scripts/minifirewall_status > /dev/null
    else
      /sbin/iptables -L -n | grep -q -E "^(DROP\s+(udp|17)|ACCEPT\s+(icmp|1))\s+--\s+0\.0\.0\.0\/0\s+0\.0\.0\.0\/0\s*$"
    fi
  fi
}

summary_critical() {
  summary="CRITICAL: $1"
  [ "${final_rc}" -le 2 ] && final_rc=2
}
summary_warning() {
  summary="WARNING: $1"
  [ "${final_rc}" -le 1 ] && final_rc=1
}
summary_ok() {
  summary="OK: $1"
  [ "${final_rc}" -le 0 ] && final_rc=0
}
append_details() {
  if [ -z "${details}" ]; then
    details="${1}\n"
  else
    details="${details}$1\n"
  fi
}

main() {
  check_result=$( /etc/init.d/minifirewall check-active-config )
  check_rc=$?

  if [ ${check_rc} -eq 0 ]; then
    append_details "configuration is up-to-date"
    summary_ok "minifirewall is started and configuration is up-to-date"
  else
    if echo "${check_result}" | grep --ignore-case --quiet --regexp 'usage'; then
      append_details "minifirewall is too old to check active configuration"
    else
      case "${check_rc}" in
          1)
            summary_warning "minifirewall configuration state is unknown"
          ;;
          2)
            summary_critical "minifirewall is started, but configuration is outdated"
            append_details "configuration is outdated"
          ;;
          *)
            summary_unchk "minifirewall configuration state is unknown"
          ;;
      esac
      append_details "=> run '/etc/init.d/minifirewall check-active-config' for details"
    fi
  fi

  printf "%s\n\n%s\n" "${summary}" "${details}"

  exit "${final_rc}"
}

main
