#!/bin/sh

set -u

final_rc=0
summary=""
details=""

is_alert5_enabled() {
  # It's not very clear how to reliably detect if a SysVinit script
  # wrapped in a systemd unit is enabled or not.
  # Even when the script is not started in any run level, systemd says "active".
  # So we test the SysVinit script path:
  # if present, we test for an rc2.d symlink
  # if missing, we ask systemd if a unit is active or not.
  if test -f /etc/init.d/alert5; then
    test -f /etc/rc2.d/S*alert5
  else
    systemctl is-enabled alert5 | grep -q "^enabled$"
  fi
}

is_minifirewall_enabled_alert5() {
  # TODO: instead of nested conditionals, we could loop with many possible paths
  # and grep the first found, or error if none is found
  if test -f /etc/rc2.d/S*alert5; then
    grep -q "^/etc/init.d/minifirewall" /etc/rc2.d/S*alert5
  else
    if test -f /usr/share/scripts/alert5.sh; then
      grep -q "^/etc/init.d/minifirewall" /usr/share/scripts/alert5.sh
    else
      return_critical "No Alert5 scripts has been found."
    fi
  fi
}

is_minifirewall_enabled_systemd() {
  systemctl is-enabled minifirewall.service >/dev/null 2>&1
}
is_minifirewall_native_systemd() {
  systemctl list-unit-files minifirewall.service | grep minifirewall.service | grep --quiet -invert--match generated
}

is_minifirewall_started() {
  if is_minifirewall_systemd; then
    systemctl is-active minifirewall.service >/dev/null 2>&1
  else
    if test -x /usr/share/scripts/minifirewall_status; then
      /usr/share/scripts/minifirewall_status > /dev/null
    else
      /sbin/iptables -L -n | grep -q -E "^(DROP\s+(udp|17)|ACCEPT\s+(icmp|1))\s+--\s+0\.0\.0\.0\/0\s+0\.0\.0\.0\/0\s*$"
    fi
  fi
}
minifirewall_version() {
  if [ -x /usr/local/sbin/minifirewall ]; then
    /usr/local/sbin/minifirewall version | cut -d ' ' -f 3 | grep --extended-regexp "^[0-9]+\.[0-9]+\S*$" 2>/dev/null
  else
    /etc/init.d/minifirewall version | cut -d ' ' -f 3 | grep --extended-regexp "^[0-9]+\.[0-9]+\S*$" 2>/dev/null
  fi
}

summary_critical() {
  summary="CRITICAL: $1"
  [ "${final_rc}" -le 2 ] && final_rc=2
}
summary_warning() {
  summary="WARNING: $1"
  [ "${final_rc}" -le 1 ] && final_rc=1
}
summary_ok() {
  summary="OK: $1"
  [ "${final_rc}" -le 0 ] && final_rc=0
}
append_details() {
  if [ -z "${details}" ]; then
    details="${1}\n"
  else
    details="${details}$1\n"
  fi
}

main() {
  if is_minifirewall_native_systemd; then
    if is_minifirewall_enabled_systemd; then
      append_details "minifirewall is enabled"
      if is_minifirewall_started; then
        append_details "minifirewall is started"
        summary_ok "minifirewall is started"
      else
        append_details "minifirewall is stopped"
        summary_critical "minifirewall is stopped, but enabled in systemd"
      fi
    else
      append_details "minifirewall is not enabled (systemd)"
      if is_minifirewall_started; then
        append_details "minifirewall is started"
        summary_warning "minifirewall is started, but disabled in systemd"
      else
        append_details "minifirewall is stopped"
        summary_ok "minifirewall is stopped and disabled in systemd"
      fi
    fi
  else
    if is_alert5_enabled; then
      append_details "alert5 is enabled"

      if is_minifirewall_enabled_alert5; then
        append_details "minifirewall is enabled (alert5)"

        if is_minifirewall_started; then
          append_details "minifirewall is started"
          summary_ok "minifirewall is started"
        else
          append_details "minifirewall is stopped"
          summary_critical "minifirewall is stopped, but enabled in alert5"
        fi
      else
        append_details "minifirewall is disabled"

        if is_minifirewall_started; then
          append_details "minifirewall is started"
          summary_warning "minifirewall is started, but disabled in alert5"
        else
          append_details "minifirewall is stopped"
          summary_ok "minifirewall is stopped, but disabled in alert5"
        fi
      fi
    else
      append_details "alert5 is disabled"

      if is_minifirewall_started; then
        append_details "minifirewall is started"
        summary_warning "minifirewall is started, but alert5 is disabled"
      else
        append_details "minifirewall is stopped"
        summary_ok "minifirewall is stopped and alert5 is disabled"
      fi
    fi
  fi

  minifirewall_version=$(minifirewall_version)
  append_details "minifirewall version is ${minifirewall_version:-unknown}"

  printf "%s\n\n%s\n" "${summary}" "${details}"

  exit "${final_rc}"
}

main
