#!/bin/sh

set -u

final_rc=0
summary=""
details=""

summary_critical() {
  summary="CRITICAL: $1"
  [ "${final_rc}" -le 2 ] && final_rc=2
}
summary_warning() {
  summary="WARNING: $1"
  [ "${final_rc}" -le 1 ] && final_rc=1
}
summary_ok() {
  summary="OK: $1"
  [ "${final_rc}" -le 0 ] && final_rc=0
}
append_details() {
  if [ -z "${details}" ]; then
    details="${1}\n"
  else
    details="${details}$1\n"
  fi
}

main() {
  check_result=$( /etc/init.d/minifirewall check-active-config )
  check_rc=$?

  if [ ${check_rc} -eq 0 ]; then
    append_details "configuration is up-to-date"
    summary_ok "minifirewall is started and configuration is up-to-date"
  else
    if echo "${check_result}" | grep --ignore-case --quiet --regexp 'usage'; then
      summary_ok "too old to check"
      append_details "minifirewall is too old to check active configuration"
    else
      case "${check_rc}" in
          1)
            summary_warning "minifirewall configuration state is unknown"
          ;;
          2)
            summary_critical "minifirewall is started, but configuration is outdated"
            append_details "configuration is outdated"
          ;;
          *)
            summary_unchk "minifirewall configuration state is unknown"
          ;;
      esac
      append_details "=> run '/etc/init.d/minifirewall check-active-config' for details"
    fi
  fi

  printf "%s\n\n%s\n" "${summary}" "${details}"

  exit "${final_rc}"
}

main
