---

- name: Molly-guard (and needrestart) is installed
  ansible.builtin.apt:
    name:
      - molly-guard
      - needrestart
    state: present

- name: Molly-guard warn-kernel-change is present
  ansible.builtin.copy:
    src: molly-guard/warn-kernel-change.sh
    dest: /etc/molly-guard/run.d/15-warn-kernel-change
    force: true
    mode: "0755"

- name: Needrestart DPKg hook is disabled
  ansible.builtin.replace:
    path: /etc/apt/apt.conf.d/99needrestart
    regexp: '^( *DPkg)'
    replace: '#\1'
