#!/bin/sh

# This hooks checks if Elasticsearch has been upgraded
# and tries to upgrade plugins

# Use grep extended syntax
package_pattern="elasticsearch"

if [ -n "${UPGRADABLE_PACKAGES_FILE}" ]; then
    if [ -f "${UPGRADABLE_PACKAGES_FILE}" ]; then

        
        if grep --quiet --extended-regexp "${package_pattern}/" "${UPGRADABLE_PACKAGES_FILE}"; then
            upgrade_bin=/usr/share/scripts/upgrade_elasticsearch_plugins.sh
            if [ -x "${upgrade_bin}" ]; then
                ${upgrade_bin}
            else
                echo "Elasticsearch has been upgraded, but ${upgrade_bin} is missing"
                echo "Please upgrade plugins manually and restart Elasticsearch" 
            fi
        fi
    else
        >&2 echo "Error: File not found: ${UPGRADABLE_PACKAGES_FILE}"
        exit 1
    fi
else
    >&2 echo "Error: missing UPGRADABLE_PACKAGES_FILE environment variable"
    exit 1
fi
