---
- ansible.builtin.include_role:
    name: evolix/apt
    tasks_from: evolix_public.yml

- name: Install PHP packages
  ansible.builtin.apt:
    name:
      - php-pear
      - php-log
      - php-net-dns2
    state: present

- name: Install PHP-FPM (multi-instance)
  ansible.builtin.apt:
    name:
      - php-fpm
    state: present
  when: evoadmin_multiinstance

- name: Install PHP5 packages (jessie)
  ansible.builtin.apt:
    name: php5-pam
    state: present
    allow_unauthenticated: True
  when: ansible_distribution_release == "jessie"
