---

- name: "/etc/alloy/config.d/10-default-loki.alloy file"
  ansible.builtin.template:
    src: 10-default-loki.alloy.j2
    dest: /etc/alloy/config.d/10-default-loki.alloy
    owner: root
    group: root
    mode: "0644"
  notify: restart alloy

# - name: "Configure local minifirewall to allow connection to loki endpoints"
#   ansible.builtin.copy:
#     dest: /etc/minifirewall.d/loki
#     content: |
#       /sbin/iptables -A INPUT -p tcp --sport {{ item | urlsplit("port") }} --dport 1024:65535 -s {{ lookup('community.general.dig',  item | urlsplit("hostname"))  }} -m state --state ESTABLISHED -j ACCEPT
#   loop: "{{ alloy_loki_default_endpoints_url }}"
#   notify: restart minifirewall

- name: "Configure loki endpoints to authorize connections from {{ ansible_hostname }}"
  ansible.builtin.lineinfile:
    path: /etc/nginx/snippets/loki_whitelist
    line: "allow {{ ansible_default_ipv4.address }}; # {{ ansible_hostname }}"
  notify: reload nginx on loki endpoints
  delegate_to: "{{ lookup('community.general.dig',  item | urlsplit('hostname')) }}"
  loop: "{{ alloy_loki_default_endpoints_url }}"

# - name: "alloy user is a member of the adm group"
#   user:
#     name: "alloy"
#     groups: "adm"
#     append: yes
#   notify: restart alloy
