- name: "/etc/alloy/config.d/10-default-prometheus.alloy file"
  ansible.builtin.template:
    src: 10-default-prometheus.alloy
    dest: /etc/alloy/config.d/10-default-prometheus.alloy
    owner: root
    group: root
    mode: "0644"
  notify: restart alloy
