- name: "/etc/alloy/config.d/prometheus-evolinux-default.alloy file"
  ansible.builtin.template:
    src: prometheus-evolinux-default.alloy
    dest: /etc/alloy/config.d/prometheus-evolinux-default.alloy
    owner: root
    group: root
    mode: "0644"
  notify: restart alloy
