---
- ansible.builtin.import_tasks: packages.yml
- ansible.builtin.import_tasks: syslog.yml
- ansible.builtin.import_tasks: user.yml
- ansible.builtin.include_role:
    name: evolix/rbenv
  vars:
    - username: "{{ redmine_user }}"
- ansible.builtin.import_tasks: config.yml
- ansible.builtin.import_tasks: mysql.yml
- ansible.builtin.import_tasks: source.yml
- ansible.builtin.import_tasks: release.yml
- ansible.builtin.import_tasks: nginx.yml
