---
- ansible.builtin.import_tasks: check.yml
- ansible.builtin.import_tasks: user.yml
- ansible.builtin.import_tasks: systemd.yml
- ansible.builtin.import_tasks: alias.yml
- ansible.builtin.import_tasks: bootstrap.yml
