---
# tasks file for hedgedoc upgrade

- name: Dump database to a file with compression
  community.postgresql.postgresql_db:
    name: "{{ hedgedoc_instance }}"
    state: dump
    target: "~/{{ hedgedoc_instance }}.sql.gz"
  become_user: postgres

- name: Stop service
  ansible.builtin.service:
    name: "{{ hedgedoc_instance }}.service"
    state: stopped

- name: Install NodeJS
  ansible.builtin.include_role:
    name: nodejs
  vars:
    - nodejs_apt_version: "{{ hedgedoc_node_version }}"
    - nodejs_install_yarn: true

- name: NodeJS is latest
  ansible.builtin.apt:
    name: nodejs
    state: latest

- name: Get app and run app setup
  become_user: "{{ hedgedoc_instance }}"
  block:
    - name: Unarchive hedgedoc archive
      ansible.builtin.unarchive:
        src: "{{ hedgedoc_download_url }}"
        dest: ~/versions
        remote_src: true
    - name: Append version to directory name
      ansible.builtin.command:
        cmd: "mv ~/versions/hedgedoc ~/versions/hedgedoc-{{ hedgedoc_version }}"
    - name: Symbolic link to unarchived version
      ansible.builtin.file:
        src: "~/versions/hedgedoc-{{ hedgedoc_version }}"
        dest: "~/hedgedoc"
        state: link
    - name: Run setup
      ansible.builtin.shell: "bin/setup"
      args:
        chdir: "~/hedgedoc"

- name: Template json config file
  ansible.builtin.template:
    src: "config.json.j2"
    dest: "~{{ hedgedoc_instance }}/hedgedoc/config.json"
    owner: "{{ hedgedoc_instance }}"
    group: "{{ hedgedoc_instance }}"
    mode: "0640"

- name: Restart services
  ansible.builtin.service:
    name: "{{ hedgedoc_instance }}.service"
    state: restarted

- name: Define variable to skip next task by default
  ansible.builtin.set_fact:
    keep_db_dump: true

- name: Remove database dump
  ansible.builtin.file:
    path: "~/{{ hedgedoc_instance }}.sql.gz"
    state: absent
  become_user: postgres
  when: keep_db_dump is undefined
  tags: clean

- name: Reload nginx conf
  ansible.builtin.service:
    name: nginx
    state: reloaded
