---

- name: "{{ lxc_php_container_name }} - Install ssmtp"
  ansible.builtin.shell:
    cmd: "DEBIAN_FRONTEND=noninteractive lxc-attach --name {{ lxc_php_container_name }} -- apt-get install --no-install-recommends --yes --force-yes ssmtp "

- name: "{{ lxc_php_container_name }} - Configure ssmtp"
  ansible.builtin.template:
    src: ssmtp.conf.j2
    dest: "{{ lxc_rootfs }}/etc/ssmtp/ssmtp.conf"
    mode: "0644"
