---

- name: "{{ lxc_php_container_name }} - Install dependency packages"
  ansible.builtin.shell:
    cmd: "DEBIAN_FRONTEND=noninteractive lxc-attach --name {{ lxc_php_container_name }} --  apt-get install -y wget gnupg"

- name: "{{ lxc_php_container_name }} - Copy keyring packages"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ lxc_rootfs }}/tmp/{{ item }}"
    mode: "0644"
    owner: root
    group: root
  loop:
    - debsuryorg-archive-keyring_2025.11.18_all.deb
    - evolix-archive-keyring_0~2025_all.deb
    # - https://packages.sury.org/php/pool/main/d/debsuryorg-archive-keyring/debsuryorg-archive-keyring_2025.11.18_all.deb
    # - https://pub.evolix.org/evolix/pool/main/e/evolix-archive-keyring/evolix-archive-keyring_0~2025_all.deb

- name: "{{ lxc_php_container_name }} - Install keyring packages"
  ansible.builtin.shell:
    cmd: "DEBIAN_FRONTEND=noninteractive lxc-attach --name {{ lxc_php_container_name }} --  apt-get install -y /tmp/{{ item }}"
  loop:
    - debsuryorg-archive-keyring_2025.11.18_all.deb
    - evolix-archive-keyring_0~2025_all.deb
    # - https://packages.sury.org/php/pool/main/d/debsuryorg-archive-keyring/debsuryorg-archive-keyring_2025.11.18_all.deb
    # - https://pub.evolix.org/evolix/pool/main/e/evolix-archive-keyring/evolix-archive-keyring_0~2025_all.deb

- name: "{{ lxc_php_container_name }} - Add sury repo"
  ansible.builtin.lineinfile:
    dest: "{{ lxc_rootfs }}/etc/apt/sources.list.d/sury.list"
    line: "{{ item }}"
    state: present
    create: yes
    mode: "0644"
  loop:
    - "deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ bullseye main"
    - "deb [signed-by=/usr/share/keyrings/pub_evolix.asc] https://pub.evolix.org/evolix bullseye-php81 main"

- name: "{{ lxc_php_container_name }} - Update APT cache"
  ansible.builtin.shell:
    cmd: "DEBIAN_FRONTEND=noninteractive lxc-attach --name {{ lxc_php_container_name }} --  apt-get update"

- name: "{{ lxc_php_container_name }} - Install PHP packages"
  ansible.builtin.shell:
    cmd: "DEBIAN_FRONTEND=noninteractive lxc-attach --name {{ lxc_php_container_name }} --  apt-get install -y php-fpm php-cli php-gd php-intl php-imap php-ldap php-mysql php-pgsql php-sqlite3 php-curl php-zip php-mbstring php-xml php-zip composer libphp-phpmailer evolix-archive-keyring debsuryorg-archive-keyring"

- name: "{{ lxc_php_container_name }} - Copy evolinux PHP configuration"
  ansible.builtin.template:
    src: z-evolinux-defaults.ini.j2
    dest: "{{ line_item }}"
    mode: "0644"
  notify: "Reload {{ lxc_php_version }}-fpm"
  loop:
    - "{{ lxc_rootfs }}/etc/php/8.1/fpm/conf.d/z-evolinux-defaults.ini"
    - "{{ lxc_rootfs }}/etc/php/8.1/cli/conf.d/z-evolinux-defaults.ini"
  loop_control:
    loop_var: line_item

- ansible.builtin.import_tasks: "mail_opensmtpd.yml"
