#!/usr/bin/env bash

CHECK_BIN=/usr/lib/nagios/plugins/check_nrpe

if ! test -f "${CHECK_BIN}"; then
    echo "${CHECK_BIN} is missing, please install nagios-nrpe-plugin package."
    exit 1
fi

for file in /etc/nagios/{nrpe.cfg,nrpe_local.cfg,nrpe.d/evolix.cfg}; do
    if [ -r ${file} ]; then
        found_command=$(grep "\[check_$1\]" "${file}" | grep -v '^[[:blank:]]*#' | tail -n1 | cut -d'=' -f2-)
    fi
    if [ -n "${found_command}" ]; then
        command="${found_command}"
    fi
done

if [ -n "${command}" ]; then
    echo "Found command in /etc/nagios (take care, in some cases, Nagios can play another command):"
    echo "    ${command}"
fi

echo "NRPE daemon output:"
"${CHECK_BIN}" -H 127.0.0.1 -c "check_$1"


