#!/usr/bin/bash
#
_monitoringctl_completion() {
    local cur=${COMP_WORDS[COMP_CWORD]};
    local prev=${COMP_WORDS[COMP_CWORD-1]};

    local action=""
    for w in "${COMP_WORDS[@]}"; do
        if [[ "${w}" =~ (status|check|enable|disable) ]]; then
            action="${w}"
            break
        fi
    done

    
    local words="--help --verbose"
    case "${action}" in
        status)
            words="${words}"
            ;;
        check)
            local checks="load disk1 https ssl"
            local check=""
            for w in "${COMP_WORDS[@]}"; do
                for c in ${checks}; do
                    if [ "${c}" == "${w}" ]; then
                        check="${w}"
                        break
                    fi
                done
            done
            if [ -z "${check}" ]; then
                words="--bypass-nrpe ${checks} ${words}"
            else
                words="--bypass-nrpe ${words}"
            fi
            ;;
        enable)
            words="${words}"
            ;;
        disable)
            if [[ "${prev}" =~ (-d|--during) ]]; then
                local last_char="${cur: -1}"
                if [ -z "${cur}" ]; then
                    COMPREPLY=("1d" "1d12h" "1h" "1h30m" "1m" "1m30s" "30s")
                else
                    if [[ "${last_char}" == "s" ]]; then
                        COMPREPLY=()
                    elif [[ "${last_char}" == "m" ]]; then
                        COMPREPLY=("${cur}30s")
                    elif [[ "${last_char}" == "h" ]]; then
                        COMPREPLY=("${cur}15m" "${cur}30m" "${cur}45m")
                    elif [[ "${last_char}" == "d" ]]; then
                        COMPREPLY=("${cur}6h" "${cur}12h" "${cur}18h")
                    elif [[ "${last_char}" =~ [0-9] ]]; then
                        if [[ "${cur}" =~ s ]]; then
                            COMPREPLY=()
                        elif [[ "${cur}" =~ m ]]; then
                            COMPREPLY=("${cur}s")
                        elif [[ "${cur}" =~ h ]]; then
                            COMPREPLY=("${cur}m")
                        elif [[ "${cur}" =~ d ]]; then
                            COMPREPLY=("${cur}h")
                        else
                            COMPREPLY=("${cur}d" "${cur}h" "${cur}m" "${cur}s")
                        fi
                    fi
                fi
                return 0
            else
                words="--during ${words}"
            fi
            ;;
        *)
            words="status check enable disable ${words}"
            ;;
    esac

    opts=();
    for i in ${words}; do
        for j in "${COMP_WORDS[@]}"; do
            if [[ "$i" == "$j" ]]; then
                continue 2
            fi
        done
        opts+=("$i")
    done

    COMPREPLY=($(compgen -W "${opts[*]}" -- "${cur}"))
    return 0

}

complete -F _monitoringctl_completion ttt

