---

- name: Verify Debian version
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_major_version is version('9', '>=')
    msg: only compatible with Debian >= 9
  when: not (evoacme_disable_debian_check | bool)

- ansible.builtin.import_tasks: certbot.yml

- ansible.builtin.import_tasks: permissions.yml

# Enable this task if you want to deploy hooks
# - ansible.builtin.include_tasks: evoacme_hook.yml
#   vars:
#     hook_name: "{{ item }}"
#   loop: []

- ansible.builtin.import_tasks: conf.yml

- ansible.builtin.import_tasks: scripts.yml
