#!/bin/sh
# Check if nfs server is running using rpcinfo

rpcinfo -u localhost nfs
if [ $? -ne 0 ]; then
    exit 2
fi

rpcinfo -t localhost nfs
if [ $? -ne 0 ]; then
    exit 2
fi

# vim: set ft=shell
