#!/bin/bash
#
# Check domains using script domains.
#
# Written by Will
#

if ! command -v domains >/dev/null; then
    echo 'UNKNOWN - Missing dependency domains.'
    exit 3
fi

domains -o nrpe -a check-dns

