#!/bin/sh
# Check if nfs server is running using rpcinfo

rpcinfo -T udp localhost nfs 3
if [ $? -ne 0 ]; then
    exit 2
fi

rpcinfo -T tcp localhost nfs
if [ $? -ne 0 ]; then
    exit 2
fi

# vim: set ft=shell
