---

- ansible.builtin.assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_major_version is version('8', '>=')
      - ansible_distribution_major_version is version('13', '<=')
    msg: This is only compatible with Debian 8 → 13

- ansible.builtin.import_tasks: main_jessie.yml
  when: ansible_distribution_release == "jessie"

- ansible.builtin.import_tasks: main_stretch.yml
  when: ansible_distribution_release == "stretch"

- ansible.builtin.import_tasks: main_buster.yml
  when: ansible_distribution_release == "buster"

- ansible.builtin.import_tasks: main_bullseye.yml
  when: ansible_distribution_release == "bullseye"

- ansible.builtin.import_tasks: main_bookworm.yml
  when: ansible_distribution_release == "bookworm"

- ansible.builtin.import_tasks: main_trixie.yml
  when: ansible_distribution_release == "trixie"
