FROM gitea.evolix.org/evolix/evodocker/ph8.2

#FROM debian:12-slim
#
#RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
#	&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
#	&& localedef -i fr_FR -c -f ISO-8859-1 -A /usr/share/locale/locale.alias fr_FR.iso88591 \
#    && localedef -i fr_FR -c -f UTF-8 -A /usr/share/locale/locale.alias fr_FR.UTF-8
#
#RUN apt-get update && apt-get install -y \
#        php \
#        php-fpm \
#        php-cli \
#        php-gd \
#        php-intl \
#        php-imap \
#        php-ldap \
#        php-mcrypt \
#        php-mysql \
#        php-pgsql \
#        php-sqlite3 \
#        php-php-gettext \
#        php-curl \
#        php-ssh2 \
#        php-zip \
#        php-mbstring \
#        composer \
#        libphp-phpmailer \
#        postfix
#
#RUN printf 'include=/etc/php/evolinux-common/fpm/pool.d/*.conf\ninclude=/etc/php/evolinux-8.2/fpm/pool.d/*.conf\n' >> /etc/php/8.2/fpm/php-fpm.conf
##RUN printf 'include=/etc/php/*/fpm/pool.d/*.conf\n' >> /etc/php/8.2/fpm/php-fpm.conf
### XXX php-cli don't support dynamical configuration directory, unlike php-fpm
#RUN ln -s /etc/php/evolinux-common/cli/evolinux-defaults.ini /etc/php/8.2/cli/conf.d/z-evolinux-common-defaults.ini && \
#    ln -s /etc/php/evolinux-common/cli/evolinux-custom.ini /etc/php/8.2/cli/conf.d/zzz-evolinux-common-custom.ini && \
#    ln -s /etc/php/evolinux-8.2/cli/evolinux-defaults.ini /etc/php/8.2/cli/conf.d/zz-evolinux-8.2-defaults.ini && \
#    ln -s /etc/php/evolinux-8.2/cli/evolinux-custom.ini /etc/php/8.2/cli/conf.d/zzzz-evolinux-8.2-custom.ini
#
## TODO Do we need to add an entrypoint?
##ENTRYPOINT ["php-fpm8.2"]
