#Type Path                                     Mode User Group Age         Argument
# XXX Need since podman-systemd.unit doesn't support optional "Mount"
# https://github.com/containers/podman/issues/26719
d     /var/run/mysqld                          0755 -    -     -           -
