---

- ansible.builtin.assert:
    that:
      - evomaintenance_api_endpoint is not none
      - evomaintenance_api_key is not none
    msg: evomaintenance api variables must be set
  when: evomaintenance_hook_api | bool

- name: Configuration is installed
  ansible.builtin.template:
    src: evomaintenance.j2
    dest: /etc/evomaintenance.cf
    mode: "0600"
    force: "{{ evomaintenance_force_config | bool }}"
  tags:
    - evomaintenance

- name: Append default users and groups allowed to sudo evomaintenance to custom ones
  set_fact:
    evomaintenance_sudoers: "{{ evomaintenance_default_sudoers + evomaintenance_custom_sudoers }}"

- name: Sudoers permission is set
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/evolinux
    regex: '%{{ item }}.*NOPASSWD.*/usr/share/scripts/evomaintenance.sh'
    line: '%{{ item }}  ALL = NOPASSWD: /usr/share/scripts/evomaintenance.sh'
    validate: /usr/sbin/visudo -cf %s
    create: yes
    mode: "0440"
  loop: "{{ evomaintenance_sudoers }}"
