---

- ansible.builtin.include_role:
    name: evolix/drbd
  when: kvm_install_drbd

- ansible.builtin.import_tasks: lvm.yml

- ansible.builtin.import_tasks: ssh.yml

- ansible.builtin.import_tasks: packages.yml

- ansible.builtin.import_tasks: munin.yml

- ansible.builtin.import_tasks: images.yml

- ansible.builtin.import_tasks: tools.yml

- ansible.builtin.import_tasks: firewall.yml
