#!/usr/bin/env bash

# If this script isn't run as root, then, re-run it with sudo.
if [ "$EUID" -ne 0 ]; then
    sudo $(readlink -f  ${BASH_SOURCE[0]}) "$@"
    exit 0;
fi;

evolixContainerVersion=$(grep SetHandler /etc/apache2/sites-enabled/$LOGNAME.conf 2>/dev/null | grep -m 1 -o 'fpm[0-9][0-9]' | head -n 1 | sed 's/php//g' | sed 's/fpm//g')

if [ "$evolixContainerVersion" != "" ]; then
    sudo lxc-attach -n php$evolixContainerVersion -- su - $LOGNAME -c "cd \"${PWD@E}\" && php /home/$LOGNAME/bin/composer ${*@Q}"
else
    # TODO: fallback?
    # command php $*
    echo "could not determine \$evolixContainerVersion"
    exit 1
fi
