#!/usr/bin/env bash

# If this script isn't run as root, then, re-run it with sudo.
if [ "$EUID" -ne 0 ]; then
    sudo PHP_UMASK="${PHP_UMASK}" $(readlink -f  ${BASH_SOURCE[0]}) "$@"
    exit 0;
fi;

# Try Apache (the usual case)
if [ -e "/etc/apache2/sites-enabled/$LOGNAME.conf" ]; then
    pattern=SetHandler
    vhostfile=/etc/apache2/sites-enabled/"${LOGNAME}".conf
elif [ -e "/etc/nginx/sites-enabled/$LOGNAME.conf" ]; then
    pattern=fastcgi_pass
    vhostfile=/etc/nginx/sites-enabled/"${LOGNAME}".conf
fi;

PHPVersion=$(grep $pattern "${vhostfile}" 2>/dev/null | grep -m 1 -o 'fpm[0-9][0-9]' | head -n 1 | sed 's/php//g' | sed 's/fpm//g')

# If $PHPVersion is empty, look for "SetHandler" in the includes.
if [ "$PHPVersion" == "" ]; then
    includes=$(grep -w "Include" "${vhostfile}" | uniq | awk '{print $2}')
    for f in "$includes"; do
        # Relative path -> absolute
        if [ ${f:0:1} != "/" ]; then
            f="/etc/apache2/${f}"
        fi

        # Grep again
        PHPVersion=$(grep $pattern "${f}" 2>/dev/null | grep -m 1 -o 'fpm[0-9][0-9]' | head -n 1 | sed 's/php//g' | sed 's/fpm//g')
        if [ "$PHPVersion" != "" ]; then
            break
        fi
    done
fi

if [ "$PHPVersion" != "" ]; then
    lxc-attach -n php$PHPVersion -- su - $LOGNAME -c "umask ${PHP_UMASK} > /dev/null; cd \"${PWD@E}\" && php ${*@Q}"
else
    # TODO: fallback?
    # command php $*
    echo "ERROR - Could not determine \$PHPVersion - Are you a web account ?"
    exit 1
fi
