# The "php" profile for php-fpm services, derived from "trusted" profile

[Service]
# From "trusted" profile
MountAPIVFS=yes
PrivateTmp=yes
BindPaths=/run
RuntimeDirectory=php
RuntimeDirectoryPreserve=yes
BindReadOnlyPaths=/etc/machine-id
BindReadOnlyPaths=/etc/resolv.conf

# Specific to "php" profile
## Users
BindPaths=/home
BindReadOnlyPaths=/etc/passwd
BindReadOnlyPaths=/etc/shadow
BindReadOnlyPaths=/etc/group
BindReadOnlyPaths=/etc/gshadow
## Network
BindReadOnlyPaths=/etc/hosts
BindReadOnlyPaths=/etc/gai.conf
## Time
BindReadOnlyPaths=/etc/timezone
BindReadOnlyPaths=/etc/localtime
## Mail
BindPaths=/var/spool/postfix
BindReadOnlyPaths=/etc/mailname
## MySQL
BindPaths=/run/mysqld
## PHP
BindPaths=/var/log
# XXX PHP's config mount point doesn't specify the version as it's not possible
#     to do so with systemd directives.
BindReadOnlyPaths=/etc/php
#BindReadOnlyPaths=/etc/evo-php:/etc/php
# XXX PHP's 5 config is in a sperate directory
BindReadOnlyPaths=-/etc/php5


# test
## XXX Of the form: phpX.Y-fpm
Environment="UNIT_NAME=%N"
