---

- name: Install java and lsof packages
  ansible.builtin.command:
    cmd: "lxc-attach -n {{ name }} -- apt-get install -y default-jre-headless lsof"

- name: "Download Solr {{ solr_version }}"
  ansible.builtin.get_url:
    url: "{{ tarball_url }}"
    dest: "{{ tarball_path }}"
    mode: '0644'
  vars:
    tarball_url: >-
      {%- if solr_version is version('9.0.0', '<') -%}
        https://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz
      {%- else -%}
        https://archive.apache.org/dist/solr/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz
      {%- endif -%}

- name: "Extract solr-{{ solr_version }}.tgz"
  ansible.builtin.unarchive:
    src: "{{ tarball_path }}"
    dest: /var/lib/lxc/{{ name }}/rootfs/root/
    remote_src: yes

- name: "Make sure /home/solr exists"
  ansible.builtin.file:
    path: /home/solr/{{ name }}
    recurse: yes
    state: directory
    mode: '0755'

- name: "Install Solr {{ solr_version }}"
  ansible.builtin.command:
    cmd: "lxc-attach -n {{ name }} -- /root/solr-{{ solr_version }}/bin/install_solr_service.sh /root/solr-{{ solr_version }}.tgz -d /home/solr/{{ name }} -p {{ solr_port }}"

- name: "Listen on all interfaces"
  ansible.builtin.blockinfile:
    dest: "/var/lib/lxc/{{ name }}/rootfs/etc/default/solr.in.sh"
    marker: "# {mark} ANSIBLE MANAGED"
    block: |
      SOLR_JETTY_HOST="0.0.0.0"
    insertafter: EOF
  when: "solr_version is version('9.0.0', '>=')"
  notify: "Restart Solr"
