#!/bin/sh
#
# This mmdebstrap hook is run before the cleaning up of the image creation process.
# It copies, to the host, non existant PHP config files from the image.

set -u

php_config_dir="/etc/php5/"

# TODO Do we want to fail if the image doens't contain php configs
if [ -d "$1/${php_config_dir}" ]; then
    rsync -aASq --ignore-existing --relative \
            "$1/./${php_config_dir}" \
            /
fi


