#!/bin/sh
# 
# This mmdebstrap hook is run before any package is extracted in the chroot and
# populate it with the host's locale config.

set -u
set -e

rsync -aASq \
        "/etc/locale.gen" \
        "$1/etc/locale.gen"
