---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart apache2 backend
  ansible.builtin.systemd_service:
    name: "apache2@evoadmin.service"
    state: restarted
  when: evoadmin_enable_vhost | bool

- name: Reload apache2 backend
  ansible.builtin.systemd_service:
    name: "apache2@evoadmin.service"
    state: reloaded
  when: evoadmin_enable_vhost | bool

- name: Reload apache2 front
  ansible.builtin.systemd_service:
    name: "apache2@front.service"
    state: reloaded

- name: "Reload php-fpm"
  ansible.builtin.systemd_service:
    name: >-
      {%- if ansible_distribution_release == "trixie" -%}
        php8.4-fpm.service
      {%- else -%}
        {{ undef() }}
      {%- endif -%}
    state: "reloaded"

- name: reload apache2
  ansible.builtin.service:
    name: apache2
    state: reloaded

- name: restart apache2
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: newaliases
  ansible.builtin.command:
    cmd: newaliases
