---

- name: dependencies are satisfied (legacy)
  ansible.builtin.apt:
    name: iptables
    state: present

- name: init script is copied (legacy)
  ansible.builtin.template:
    src: legacy/minifirewall.sh.j2
    dest: /etc/init.d/minifirewall
    force: "{{ minifirewall_force_upgrade_script | default(False) }}"
    mode: "0700"
    owner: root
    group: root

- name: configuration is copied (legacy)
  ansible.builtin.copy:
    src: legacy/minifirewall.conf
    dest: "{{ minifirewall_main_file }}"
    force: "{{ minifirewall_force_upgrade_config | default(False) }}"
    mode: "0600"
    owner: root
    group: root
