---

- ansible.builtin.include_role:
    name: evolix/remount-usr

- name: /usr/share/scripts exists
  ansible.builtin.file:
    dest: /usr/share/scripts
    mode: "0700"
    owner: root
    group: root
    state: directory

- name: minifirewall_status is installed
  ansible.builtin.copy:
    src: minifirewall_status
    dest: /usr/share/scripts/minifirewall_status
    force: "{{ minifirewall_force_update_nrpe_scripts | bool }}"
    mode: "0700"
    owner: root
    group: root

- name: Is NRPE installed?
  ansible.builtin.stat:
    path: /etc/nagios/nrpe.d/evolix.cfg
  register: nrpe_evolix_cfg
  
- name: Install checks
  ansible.builtin.include_tasks: check.yml
  loop_control:
    loop_var: _check
  loop:
    - check_minifirewall
    - check_minifirewall_config
  when: nrpe_evolix_cfg.stat.exists
