---

- name: Remount /usr if needed
  ansible.builtin.include_role:
    name: evolix/remount-usr

- name: /usr/share/scripts exists
  ansible.builtin.file:
    dest: /usr/share/scripts
    mode: "0700"
    owner: root
    group: root
    state: directory

- name: blacklist-countries.sh is copied
  ansible.builtin.copy:
    src: "upstream/{{ item }}"
    dest: /usr/share/scripts/
    force: "no"
    mode: "0700"
    owner: root
    group: root
  loop:
    - "utils/blacklist-as.sh"
    - "utils/blacklist-asiapacific.sh"
    - "utils/blacklist-countries.sh"
    - "utils/ripe.sh"
    - "utils/rpki.sh"
