---

- ansible.builtin.include_role:
    name: evolix/apt
    tasks_from: backports.yml
  tags:
    - haproxy
    - packages

- ansible.builtin.set_fact:
    haproxy_backports_packages: "{{ haproxy_backports_packages_stretch }}"
  when: ansible_distribution_release == 'stretch'

- ansible.builtin.set_fact:
    haproxy_backports_packages: "{{ haproxy_backports_packages_buster }}"
  when: ansible_distribution_release == 'buster'

- ansible.builtin.set_fact:
    haproxy_backports_packages: "{{ haproxy_backports_packages_bullseye }}"
  when: ansible_distribution_release == 'bullseye'

- ansible.builtin.set_fact:
    haproxy_backports_packages: "{{ haproxy_backports_packages_bookworm }}"
  when: ansible_distribution_release == 'bookworm'

- name: update apt
  ansible.builtin.apt:
    update_cache: yes
  tags:
    - haproxy
    - packages
