# Install node-exporter

- name: "prometheus-node-exporter installed"
  ansible.builtin.apt:
    name: "prometheus-node-exporter"
    state: "present"

# Configure prometheus-node-exporter.service

- name: "/etc/prometheus/node-exporter/ directory"
  ansible.builtin.file:
    path: "/etc/prometheus/node-exporter/"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "/etc/prometheus/node-exporter/evolinux-default.args file"
  ansible.builtin.template:
    src: "node-exporter/evolinux-default.args"
    dest: "/etc/prometheus/node-exporter/evolinux-default.args"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "/etc/prometheus/node-exporter/evolinux-custom.args file"
  ansible.builtin.template:
    src: "node-exporter/evolinux-custom.args"
    dest: "/etc/prometheus/node-exporter/evolinux-custom.args"
    owner: "root"
    group: "root"
    mode: "0644"
    force: false

# Configure and start prometheus-node-exporter.service

- name: "/etc/systemd/system/prometheus-node-exporter.service.d/ directory"
  ansible.builtin.file:
    path: "/etc/systemd/system/prometheus-node-exporter.service.d/"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "/etc/systemd/system/prometheus-node-exporter.service.d/evolinux-default.conf file"
  ansible.builtin.template:
    src: "prometheus-node-exporter.service.d/evolinux-default.conf"
    dest: "/etc/systemd/system/prometheus-node-exporter.service.d/evolinux-default.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "restart prometheus-node-exporter"
    - "daemon-reload"

# Configure vmagent to scrape node-exporter

- name: "/etc/victoria-metrics/scrape.d/node-exporter.yml file"
  ansible.builtin.template:
    src: "scrape.d/node-exporter.yml"
    dest: "/etc/victoria-metrics/scrape.d/node-exporter.yml"
    owner: "_victoria-metrics"
    group: "_victoria-metrics"
    mode: "0640"
  notify: "reload vmagent"
