# Install VMAgent

- name: "victoria-metrics installed"
  ansible.builtin.apt:
    name: "victoria-metrics"
    state: "present"
  register: "victoriametrics_installed"

- name: "victoria-metrics.service stopped and disabled"
  ansible.builtin.service:
    name: "victoria-metrics.service" 
    state: "stopped"
    enabled: false
  # We don't want to touch that service if we didn't installed the package
  # just now. Otherwise we could stop actual victoria-metrics.service instance.
  when: "victoriametrics_installed is changed"

# Configure VMAgent

# TODO does /etc/victoria-metrics/ is created when the package is installed ?

## Configure vmagent.service

- name: "/etc/victoria-metrics/vmagent.d/ directory"
  ansible.builtin.file:
    path: "/etc/victoria-metrics/vmagent.d/"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0750"

- name: "/etc/victoria-metrics/vmagent.d/z-evolinux-default.env file"
  ansible.builtin.template:
    src: "vmagent.d/z-evolinux-default.env"
    dest: "/etc/victoria-metrics/vmagent.d/z-evolinux-default.env"
    owner: "root"
    group: "root"
    mode: "0640"

- name: "/etc/victoria-metrics/vmagent.d/zzz-evolinux-custom.env file"
  ansible.builtin.template:
    src: "vmagent.d/zzz-evolinux-custom.env"
    dest: "/etc/victoria-metrics/vmagent.d/zzz-evolinux-custom.env"
    owner: "root"
    group: "root"
    mode: "0640"
    force: false

## Configure victoria-metrics scraping

- name: "/etc/victoria-metrics/scrape.d/ directory"
  ansible.builtin.file:
    path: "/etc/victoria-metrics/scrape.d/"
    state: "directory"
    owner: "_victoria-metrics"
    group: "_victoria-metrics"
    mode: "0750"

- name: "/etc/victoria-metrics/scrape.yml file"
  ansible.builtin.template:
    src: "scrape.yml"
    dest: "/etc/victoria-metrics/scrape.yml"
    owner: "_victoria-metrics"
    group: "_victoria-metrics"
    mode: "0640"

# Create and start vmagent.service

- name: "vmagent.service exists"
  ansible.builtin.template:
    src: "vmagent.service"
    dest: "/etc/systemd/system/vmagent.service"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "daemon-reload"

- name: "vmagent.service enabled and started"
  ansible.builtin.systemd:
    name: "vmagent.service"
    state: "started"
    enabled: true
