---

- ansible.builtin.set_fact:
    mysql_restart_handler_name: "{{ mysql_restart_if_needed | bool | ternary('restart mysql', 'restart mysql (noop)') }}"

- ansible.builtin.import_tasks: packages.yml

- ansible.builtin.import_tasks: users.yml

- ansible.builtin.import_tasks: config.yml

- ansible.builtin.import_tasks: datadir.yml

- ansible.builtin.import_tasks: tmpdir.yml

- ansible.builtin.import_tasks: nrpe.yml

- ansible.builtin.import_tasks: munin.yml

- ansible.builtin.import_tasks: log2mail.yml

- ansible.builtin.import_tasks: utils.yml
