- name: LDAP packages are installed
  ansible.builtin.apt:
    name:
      - slapd
      - ldap-utils
      - ldapvi
      - shelldap
      - libldap-common
    state: present
    update_cache: yes

- name: change slapd listen ip:port
  ansible.builtin.lineinfile:
    dest: /etc/default/slapd
    regexp: 'SLAPD_SERVICES=.*'
    line: "SLAPD_SERVICES=\"{{ ldap_listen }}\""
  notify: restart slapd

- name: ldapvirc file
  ansible.builtin.import_tasks: ldapvirc.yml

- name: nagios config file for LDAP
  ansible.builtin.import_tasks: nagios.yml

- name: initialize database
  ansible.builtin.import_tasks: init.yml
  when: not root_ldapvirc_path.stat.exists
