---
- name: "Reload apache front vhost"
  ansible.builtin.systemd_service:
    name: "apache2@{{ apache_multi_front_vhost_name }}.service"
    state: "reloaded"

- name: "Restart munin-node"
  ansible.builtin.systemd_service:
    name: "munin-node"
    state: "restarted"
