#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2024 Evolix
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Replaced by monitoringctl.
# check-local executable is kept for retrocompatibility purposes.

monitoringctl check "${1}"

