---
- name: Create private key with password protection
  community.crypto.openssl_privatekey:
    path: "{{ pki_dir }}/private/ca.key"
    passphrase: "{{ pki_ca_password }}"
    cipher: auto

- name: Create certificate signing request (CSR) for CA certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ pki_dir }}/private/ca.key"
    privatekey_passphrase: "{{ pki_ca_password }}"
    common_name: "{{ pki_ca_common_name }}"
    use_common_name_for_san: false
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: yes
    key_usage:
      - keyCertSign
    key_usage_critical: true
  register: ca_csr

- name: Create self-signed CA certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ pki_dir }}/certs/ca.crt"
    csr_content: "{{ ca_csr.csr }}"
    privatekey_path: "{{ pki_dir }}/private/ca.key"
    privatekey_passphrase: "{{ pki_ca_password }}"
    provider: selfsigned
