---
# Misc

- name: Install python 2 cryptography
  ansible.builtin.apt:
    name: python-cryptography
    state: present
  when: ansible_python['executable'] == "/usr/bin/python"

- name: Install python 3 cryptography
  ansible.builtin.apt:
    name: python3-cryptography
    state: present
  when: ansible_python['executable'] == "/usr/bin/python3"

- name: Creates PKI tree directories
  ansible.builtin.file:
    path: "{{ item }}"
    mode: 0700
    state: directory
  loop:
    - "{{ pki_dir }}/certs"
    - "{{ pki_dir }}/private"
    - "{{ pki_dir }}/csr"

# Create Certificat Authority (CA)

- ansible.builtin.import_tasks: ca.yml
  when: inventory_hostname == pki_ca_host and not ansible_check_mode

# Create new signed certificate

- name: Create private key for new certificate
  community.crypto.openssl_privatekey:
    path: "{{ pki_dir }}/private/{{ pki_cert_common_name }}.key"

- name: Check whether Certificate Signing Request (CSR) exists
  ansible.builtin.stat:
    path: "{{ pki_dir }}/csr/{{ pki_cert_common_name }}.csr"
  register: csr_exists

- name: Read existing CSR if it exists
  ansible.builtin.slurp:
    src: "{{ pki_dir }}/csr/{{ pki_cert_common_name }}.csr"
  when: csr_exists.stat.exists
  register: csr

- name: Create Certificate Signing Request (CSR) for new certificate
  community.crypto.openssl_csr_pipe:
    content: "{{ (csr.content | b64decode) if csr_exists.stat.exists else omit }}"
    privatekey_path: "{{ pki_dir }}/private/{{ pki_cert_common_name }}.key"
    common_name: "{{ pki_cert_common_name }}"
  register: csr

- name: Write CSR file
  ansible.builtin.copy:
    dest: "{{ pki_dir }}/csr/{{ pki_cert_common_name }}.csr"
    content: "{{ csr.csr }}"
  when: csr is changed and not ansible_check_mode

- name: Check whether certificate exists
  ansible.builtin.stat:
    path: "{{ pki_dir }}/certs/{{ pki_cert_common_name }}.crt"
  register: certificate_exists

- name: Read existing certificate if exists
  ansible.builtin.slurp:
    src: "{{ pki_dir }}/certs/{{ pki_cert_common_name }}.crt"
  when: certificate_exists.stat.exists
  register: certificate

- name: Sign certificate with CA
  community.crypto.x509_certificate_pipe:
    content: "{{ (certificate.content | b64decode) if certificate_exists.stat.exists else omit }}"
    csr_content: "{{ csr.csr }}"
    provider: ownca
    ownca_path: "{{ pki_dir }}/certs/ca.crt"
    ownca_privatekey_path: "{{ pki_dir }}/private/ca.key"
    ownca_privatekey_passphrase: "{{ pki_ca_password }}"
  delegate_to: "{{ pki_ca_host | mandatory }}"
  register: certificate
  when: not ansible_check_mode

- name: Write certificate file
  ansible.builtin.copy:
    dest: "{{ pki_dir }}/certs/{{ pki_cert_common_name }}.crt"
    content: "{{ certificate.certificate }}"
  when: certificate is changed and not ansible_check_mode

- name: Write certificate file on the CA host
  ansible.builtin.copy:
    dest: "{{ pki_dir }}/certs/{{ pki_cert_common_name }}.crt"
    content: "{{ certificate.certificate }}"
  delegate_to: "{{ pki_ca_host | mandatory }}"
  when: certificate is changed and not ansible_check_mode


# CA certificate

- name: Check whether CA certificate exists
  ansible.builtin.stat:
    path: "{{ pki_dir }}/certs/ca.crt"
  delegate_to: "{{ pki_ca_host | mandatory }}"
  register: ca_certificate_exists

- name: Read existing CA certificate if exists
  ansible.builtin.slurp:
    src: "{{ pki_dir }}/certs/ca.crt"
  when: ca_certificate_exists.stat.exists
  delegate_to: "{{ pki_ca_host | mandatory }}"
  register: ca_certificate

- name: Write CA certificate file
  ansible.builtin.copy:
    dest: "{{ pki_dir }}/certs/ca.crt"
    content: "{{ ca_certificate.content | b64decode }}"
  register: ca_certificate

- name: Set fact, _pki_changed
  when: certificate is changed or ca_certificate is changed
  ansible.builtin.set_fact:
    _pki_changed: True
