---

- name: "Debconf settings"
  ansible.builtin.debconf:
    name: postfix
    question: "{{ item.key }}"
    value: "{{ item.value }}"
    vtype: "{{ item.type }}"
  loop:
    - { key: 'postfix/main_mailer_type', type: 'string', value: 'No configuration' }
    - { key: 'postfix/mailname',         type: 'string', value: "{{ evolinux_fqdn | default(ansible_fqdn) }}" }

- name: Postfix packages are installed
  ansible.builtin.apt:
    name:
      - postfix
      - mailgraph
    state: present
  tags:
    - postfix

- name: exim4 is absent
  ansible.builtin.apt:
    name:
      - exim4
      - exim4-base
      - exim4-config
      - exim4-daemon-light
    purge: yes
    state: absent
  tags:
    - postfix
  when: postfix_purge_exim | bool

- name: Get stats for /etc/postfix/main.cf
  ansible.builtin.stat:
    path: /etc/postfix/main.cf
    get_checksum: false
  register: main_cf
  tags:
    - postfix

- name: compute main.cf SHA1 checksum
  ansible.builtin.shell:
    cmd: 'grep --invert-match --extended-regexp "^(myhostname|mydestination|mailbox_command)" /etc/postfix/main.cf | sha1sum | cut -d " " -f1'
  changed_when: False
  check_mode: no
  register: main_cf_checksum
  tags:
    - postfix

- name: display checksums of known main.cf files
  ansible.builtin.debug:
    var: main_cf_known_checksums
    verbosity: 1
  tags:
    - postfix

- name: display checksum of current main.cf file
  ansible.builtin.debug:
    var: main_cf_checksum
    verbosity: 1
  tags:
    - postfix

- name: display stat of main.cf file
  ansible.builtin.debug:
    var: main_cf.stat
    verbosity: 1
  tags:
    - postfix

- name: add lines in /etc/.gitignore
  ansible.builtin.lineinfile:
    dest: /etc/.gitignore
    line: '{{ item }}'
    state: present
    create: no
  loop:
    - "postfix/sa-blacklist.access"
    - "postfix/*.db"
  tags:
    - postfix
    - etc-git
