---

- name: create minimal main.cf
  ansible.builtin.template:
    src: "{{ postfix_minimal_main_cf_path }}"
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: "0644"
    force: true
  notify: restart postfix
  when: (postfix_force_main_cf | bool) or not main_cf.stat.exists or (main_cf_checksum.stdout in main_cf_known_checksums)
  tags:
  - postfix
